name: techweek
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Terminal message with fancy sentence
        run: |
          echo "Hola chavales"

      - name: Terminal message with fancy sentence
        run: |
          echo "The name of our repository: ${{ github.repository }}."
      
      - name: Load repository
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}


